name: unit-test 

on: 
    push:
        branches:
            - main 

jobs:
    test: 
        runs-on: ubuntu-latest 
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
        
            -   name: Set up Node.js 
                uses: actions/setup-node@v4
                with:
                    node-version: '20' 
            
            -   name: Install dependencies 
                run: cd backend && npm install 
            
            -   name: Compose up the services 
                run: docker-compose up --build -d 
            
            -   name: Wait for services to be ready 
                run: sleep 10 


            -   name: run the tests 
                run: cd backend && npx mocha


